### ISSUE TITLE
Best practices with CSS & Javascript?

### ISSUE THREAD

**Issue by nmn** [bittorrent/torrent-web-tools#1]
The common best-practice on the web is to concatenate JS and CSS files to minimize HTTP calls. What is the best practice with Maelstorm?

**Comment by aaroncohen** [comment]
Minimizing files to reduce space usage will have a positive effect on loading time, but any impact of reducing file count will be minimal. We'll be following up on this with more opinionated recommendations later.

If you're inspired, we'd love to hear your experiences with various approaches.

**Comment by nmn** [comment]
I'm waiting for the Mac beta to actually try things. In the mean time I'm mostly just reading about the technology.

**Comment by matthieu-vergne** [comment]
I personaly wait for a LINUX version, which seems out of the scope because no mention of it. Don't know why.

Le 14 avril 2015 12:01:51 CEST, Naman Goel <notifications@github.com> a écrit :
>I'm waiting for the Mac beta to actually try things. In the mean time
>I'm mostly just reading about the technology.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bittorrent/torrent-web-tools/issues/1#issuecomment-92732980

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by keoghpe** [comment]
Does it say anywhere that they will release the source for Maelstrom?

**Comment by nmn** [comment]
@matthieu-vergne I think the Linux version wasn't a high priority as BitTorrent seems to be focussing on the general public.
@keoghpe I do know that Maelstrom is based on chromium, but I have no idea if they will even open-source it. I personally kind of doubt it. BitTorrent is a for-profit company after all.

That said, there have been many great experiments such [torrent-stream](https://github.com/mafintosh/torrent-stream) that pave the way for similar developments from other companies.

**Comment by keoghpe** [comment]
@nmn  I think that if they want to develop "a truly open web" then they should be putting the technology in the hands of the public.. You're right though, they are a for-profit company. Maybe if the project is successful it will inspire someone to develop an open source version.

**Comment by matthieu-vergne** [comment]
@nmn The way you mention it let think that Linux people are kind of "outsiders" (like old arguments we could find before Ubuntu becomes one of the largets "general public" Linux OSs) and thus "irrelevant people", which, I have to say, hurted my pride {'^_^}. But when the rationality come back, it seems that [the amount of Linux computers is not significant compared to other distributions](http://www.statista.com/statistics/268237/global-market-share-held-by-operating-systems-since-2009/), which I assume is what you actually meant, and I would have prefered you say it that way, speaking about "the major part of the public", rather than speaking about an ambiguous "general public". Consequently, I suggest you to pay attention on the way you highlight, in general, that some categories of people are not relevant. Providing sources to illustrate what you mean could, by the way, greatly avoid such misunderstanding.

**Comment by nmn** [comment]
@matthieu-vergne pardon my language. I really just meant to point you to fact that BitTorrent is focussing on the platforms with the largest audience first. They haven't even released the Mac version yet.

Also, what I meant by 'general public' was to say that most developers use Linux or Mac and BitTorrent doesn't seem to be focussing on developers. (I find the choice ingeresting. I think only developers will care for it in the beginning)

Of course I don't mean to deride Linux or call its users outsiders.

**Comment by matthieu-vergne** [comment]
> I find the choice ingeresting. I think only developers will care for it in the beginning

Same for me, considering we speak about designing websites. {^_^}
